# Import libraries

import pandas as pd
import streamlit as st
import altair as alt
from PIL import Image

# Page title

image = Image.open('dna_simple_counter.png')

st.image(image, use_column_width=True)

st.write("""
# DNA Nucleotide Count Web App

This app counts the nucleotide composition of query DNA!

***                  
""")

# Input Text Box

st.header('Enter DNA sequence')

sequence_input = "DNA Query\nACACTCGCTTCTGGAACGTCTGAGGTTATCAATAAGCTCCTAGTCCAGACGCCATGGGTC\nATTTCACAGAGGAGGACAAGGCTACTATCACAAGCCTGTGGGGCAAGGTGAATGTGGAAG\nATGCTGGAGGAGAAACCCTGGGAAGGTAGGCTCTGGTGACCAGGACAAGGGAGGGAAGGA\nAGGACCCTGTGCCTGGCAAAAGTCCAGGTCGCTTCTCAGGATTTGTGGCACCTTCTGACT\nGTCAAACTGTTCTTGTCAATCTCACAGGCTCCTGGTTGTCTACCCATGGACCCAGAGGTT\nCTTTGACAGCTTTGGCAACCTGTCCTCTGCCTCTGCCATCATGGGCAACCCCAAAGTCAA\nGGCACATGGCAAGAAGGTGCTGACTTCCTTGGGAGATGCCACAAAGCACCTGGATGATCT\nCAAGGGCACCTTTGCCCAGCTGAGTGAACTGCACTGTGACAAGCTGCATGTGGATCCTGA\nGAACTTCAAGGTGAGTCCAGGAGATGTTTCAGCCCTGTTGCCTTTAGTCTCGAGGCAACT\nTAGACAACGGAGTATTGATCTGAGCACAGCAGGGTGTGAGCTGTTTGAAGATACTGGGGT\nTGGGGGTGAAGAAACTGCAGAGGACTAACTGGGCTGAGACCCAGTGGTAATGTTTTAGGG\nCCTAAGGAGTGCCTCTAAAAATCTAGATGGACAATTTTGACTTTGAGAAAAGAGAGGTGG\nAAATGAGGAAAATGACTTTTCTTTATTAGATTCCAGTAGAAAGAACTTTCATCTTTCCCT\nCATTTTTGTTGTTTTAAAACATCTATCTGGAGGCAGGACAAGTATGGTCGTTAAAAAGAT\nGCAGGCAGAAGGCATATATTGGCTCAGTCAAAGTGGGGAACTTTGGTGGCCAAACATACA\nTTGCTAAGGCTATTCCTATATCAGCTGGACACATATAAAATGCTGCTAATGCTTCATTAC\nAAACTTATATCCTTTAATTCCAGATGGGGGCAAAGTATGTCCAGGGGTGAGGAACAATTG\nAAACATTTGGGCTGGAGTAGATTTTGAAAGTCAGCTCTGTGTGTGTGTGTGTGTGTGCGC\nGCGCGCGTGTGTGTGTGTGTGTCAGCGTGTGTTTCTTTTAACGTCTTCAGCCTACAACAT\nACAGGGTTCATGGTGGCAAGAAGATAGCAAGATTTAAATTATGGCCAGTGACTAGTGCTT\nGAAGGGGAACAACTACCTGCATTTAATGGGAAGGCAAAATCTCAGGCTTTGAGGGAAGTT\nAACATAGGCTTGATTCTGGGTGGAAGCTTGGTGTGTAGTTATCTGGAGGCCAGGCTGGAG\nCTCTCAGCTCACTATGGGTTCATCTTTATTGTCTCCTTTCATCTCAACAGCTCCTGGGAA\nATGTGCTGGTGACCGTTTTGGCAATCCATTTCGGCAAAGAATTCACCCCTGAGGTGCAGG\nCTTCCTGGCAGAAGATGGTGACTGCAGTGGCCAGTGCCCTGTCCTCCAGATACCACTGAG\nCTCACTGCCCATGATTCAGAGCTTTCAAGGATAGGCTTTATTCTGCAAGCAATACAAATA\nATAAATCTATTCTGCTGAGAGATCACACA"

sequence = st.text_area("Sequence input", sequence_input, height=250)
sequence = sequence.splitlines()
sequence = sequence[1:] # Skip the sequence name
sequence = ''.join(sequence) # Concatenates list to string

st.write("""
***
""")

## Prints the input DNA sequence
st.header('Input (DNA Query)')
sequence

## DNA nucleotide count
st.header('OUTPUT (DNA Nucleotide Count')

### 1. Print dictionary
st.subheader('1. Print dictionary')
def DNA_nucleotide_count(seq):
    d = dict([
        ('A', seq.count('A')),
        ('T', seq.count('T')),
        ('G', seq.count('G')),
        ('C', seq.count('C')),
    ])
    return d

X = DNA_nucleotide_count(sequence)

X_label = list(X)
X_values = list(X.values())

X
